### ISSUE TITLE
userbuffer运行起来比Itensor慢

### ISSUE THREAD

**Issue by JimmyLauren** [gesanqiu/yolov3-thread-pool#1]
你好，我这边参考您的代码，运行起来之后发现使用UserBuffer比用Itensor速度慢很多，能麻烦您指点一下嘛？非常感谢。

**Comment by fanzy1234** [comment]
您好，请教下如何将yolo模型转dlc？
我先转onnx再转dlc时报错，ValueError: Dynamic value for tensor name: 668, is not supported.
您遇到过这种问题吗？

**Comment by gesanqiu** [comment]
> 

我能想到的只有SNPE支持的operator有限，请使用SNPE支持的ONNX版本下的支持的算子，具体请参考SNPE Release Notes和ONNX的README，我只有将mobilenet的onnx转为dlc的经历，尝试了多个版本的ONNX的多种算子才通过测试。另外请不要在他人的issue里提support request，其次光从一句log判断不出什么，我并不是算法工程师，算法相关细节更简易咨询算法专业人士。

**Comment by fanzy1234** [comment]
好的下次注意，
转onnx时把dynamic_axes参数关掉就行了．
但是直接转换的模型使用gpu推理会报错．

**Comment by gesanqiu** [comment]
问题转为support request，已解决，issue close，下面贴出交流过程。

在2021年12月21日 10:07，RicardorLu<shenglu1202@163.com> 写道：
您好，
首先如转换log所言，对于非框架使用问题你可以向高通的NPU Team提case以获得更专业的支持，anyway这将是我最后一次回复你的support request，因为再深入将涉及到付费的信息。
这个问题涉及到量化的原理，所谓量化就是将浮点运算转成低比特定点计算的技术，将连续的网络参数使用“某个区间内的离散值”替代这些连续参数，以减少参数个数，高通的量化算法有几种，在snpe-dlc-quantize里可以通过参数选择，这部分细节不展开。
正如log中的min和max所示，假如你的量化输入数据集太小，比如只有一张图片，那么min和max的区间就没有太大的意义，因为它只针对这一张图片生效，那么量化不具备鲁棒性，在任何场景下精度损失都会非常严重；假如你的输入集和测试集不属于同一场景，那么这些量化参数也无法很好的反映你的测试场景，也将造成一定的误差。
所以，请问你的量化过程所输入的数据集规模是什么样的，量化的输入集和你实际应用中的测试集的场景差距有多大，我这边的建议是使用150-200张与实际应用场景一致的输入数据集进行量化。
谢谢。

在 2021-12-20 18:09:54，"刘健" <iamjianliu@163.com> 写道：
您好，不好意思再打扰下，我这边有个问题想请教下。
我这边已经可以在dsp和aip上跑模型了，但是我对比CPU、DSP、AIP的输出之后发现AIP的输出和DSP/GPU输出差距较大，我这边使用snpe-dlc-quantize工具生成量化模型的参数就只有生成AIP模型的时候加了--enable_hta这一个差别，用来量化的数据也是同一批。
请问一下您当时有没有遇到这个问题呢？然后是怎么解决的？
再次感谢~~
祝好！

在2021年12月16日 09:39，刘健<iamjianliu@163.com> 写道：
非常感谢！！！

在2021年12月15日 09:41，RicardorLu<shenglu1202@163.com> 写道：
您好，
1.支持哪种runtime跟SOC硬件有关，865具有NPU是支持AIP的，SNPE的Release Notes里应该可以找到支持的平台。
2.对于所有的算法模型，一般的开发流程是先使用SPNE自带的snpe-net-run工具先进行简单的验证，你可以在SNPE的bin/目录下找到对应平台的编译好的binary文件，据我所知qrb5165可以使用${SNPE_ROOT}/bin/aarch64-ubuntu-gcc7.5/目录下的binary。
3.DSP runtime相关的库应该放在/usr/lib/rfsa/adsp目录下，这是必须的。
谢谢。

在 2021-12-14 15:23:07，"刘健" <iamjianliu@163.com> 写道：
您好，不好意思再打扰一下，我这边在865上的ubuntu系统运行dsp环境检测程序报错，麻烦问一下这个是什么问题呢？我这边dsp相关的库都已经配置好。
在2021年12月14日 10:22，刘健<iamjianliu@163.com> 写道：
你好，感谢回复。
我这边用的aarch64-ubuntu1804的系统，请问一下这个系统上面有AIP runtime嘛？

在2021年12月14日 10:03，RicardorLu<shenglu1202@163.com> 写道：
你好，
865的GPU是单核设计，因此并不具备多线程的能力，多实例的情况下有性能衰减是很正常的，这个和GPU使用率没有关系。
从我的测试情况来看，GPU多实例情况下性能衰减大概是倍增；DSP性能衰减在yolo3这个模型上随着实例个数增加呈线性增长，在6个实例的时候大约达到1个实例的2倍耗时；但是AIP Runtime上由于AIP的带宽足够，因此性能衰减并不十分明显，6个AIP实例大约只增加10%的耗时。
谢谢。

在 2021-12-13 09:24:45，"刘健" <iamjianliu@163.com> 写道：
您好，非常感谢回复。现在暂时我用的itensor做输入输出。还有个问题想请教下，我这边多线程测试，SNPE开2个线程时间开销为开1个线程的两倍，开8个线程时间开销同样为开1个线程的8倍；开多个进程时间开销同样为开单个进程的相应倍数。同时，在开16个线程的时候我用/sys/kernel/gpu/gpu_busy测试了一下GPU使用率也才到60%左右。想请教一下这个问题该如何解决呢？

在2021年12月10日 18:53，RicardorLu<shenglu1202@163.com> 写道：
您好，
以我的理解UserBuffer类似于Nvidia平台上的UnifiedMemory，相较于ITensor来说能够减少输入输出数据的拷贝，从这个角度来说应该要比ITensor快才对，我能想到的情况UserBuffer比ITensor慢的情况只有不同的buffer在inference性能上可能会有差距。
请问能提供具体一点的log吗，比如说你的benchmark是计算了那些过程的时间以及慢了多少？但是假如是inference的性能差距，由于我不是算法工程师，所以我更建议您向高通的NPU Team提case交流这部分细节。
谢谢。
